name: Generate Snake

on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # This allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository so that the action can access it
      - uses: actions/checkout@v2

      # Generate the snake GIF
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: viswanathkasi133  # Replace with your GitHub username
          # Path for snake GIF and SVG files
          gif_out_path: github-snake/github-contribution-grid-snake.gif
          svg_out_path: github-snake/github-contribution-grid-snake.svg

      # Display the status for debugging
      - run: git status

      # Commit and push the changes to the main branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: github-snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
